Updates for the git guide
piwik/developer-documentation pull request #535
Opened 2021-08-26 04:56 UTC by tsteur

### Review

* [ ] [Functional review done](https://developer.matomo.org/guides/pull-request-reviews#functional-review-done)
* [ ] [Potential edge cases thought about](https://developer.matomo.org/guides/pull-request-reviews#potential-edge-cases-thought-about) (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [ ] [Usability review done](https://developer.matomo.org/guides/pull-request-reviews#usability-review-done) (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] [Security review done](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] [Wording review done](https://developer.matomo.org/guides/pull-request-reviews#translations-wording-review-done)
* [ ] [Code review done](https://developer.matomo.org/guides/pull-request-reviews#code-review-done)
* [ ] [Tests were added if useful/possible](https://developer.matomo.org/guides/pull-request-reviews#tests-were-added-if-usefulpossible)
* [ ] [Reviewed for breaking changes](https://developer.matomo.org/guides/pull-request-reviews#reviewed-for-breaking-changes)
* [ ] [Developer changelog updated if needed](https://developer.matomo.org/guides/pull-request-reviews#developer-changelog-updated-if-needed)
* [ ] [Documentation added if needed](https://developer.matomo.org/guides/pull-request-reviews#documentation-added-if-needed)
* [ ] Existing documentation updated if needed

2021-08-26 07:59 UTC, sgiehl requested changes

2021-08-26 07:59 UTC, sgiehl commented on docs/git.md
> +While `git push --force` works too it overwrites the entire remote branch with your local branch, `--force-with-lease` is safer as it makes sure you won't overwrite someone else's work.
That's actually not fully correct. `force-with-lease` actually only check if you local copy of origin is the same as the remote origin. So it actually prevents pushing if someone else pushed the branch in the meantime. But a simple `git fetch; git push --force-with-lease` would then work and "overwrite" the remote changes.

2021-08-26 07:59 UTC, sgiehl commented on docs/git.md
> +`git add -p`
Note: This won't work for binary files. So for example images would be skipped by this command

2021-08-26 07:59 UTC, sgiehl commented on docs/git.md
> +At Matomo we're using Git version control system. Below are some tips for using git. Below is a guide for how we work using git on the command line.
Sounds a bit weird with `Below are... Below is...` Maybe something like this sounds better?
```suggestion
At Matomo we're using Git version control system. Below are some tips for using git along with a guide for how we work using git on the command line.
```

2021-08-26 07:59 UTC, sgiehl commented on docs/git.md
> +* [Git LFS needs to be installed](https://github.com/git-lfs/git-lfs/wiki/Installation)
Should we mention that by default the lfs files won't be checked out, and that this is only needed for writing or updating UI tests. See https://developer.matomo.org/guides/tests-ui#requirements

2021-08-26 07:59 UTC, sgiehl commented on docs/git.md
> +`git clone git@github.com:matomo-org/matomo.git matomo`
Would it make sense to mention the submodules here and that a `git submodule init` is needed to initialize and check them out?

2021-08-26 07:59 UTC, sgiehl commented on docs/git.md
> +We'll give our new branch a name. The branch name ideally always contains the GitHub issue number eg `1111` or `m1111` or if it's a Jira issue then eg `dev-1111`. Optionally, a descriptive name can b
not sure if we maybe should avoid using the issue number as branch name only. At some point this might result in some weird stuff when an issue number matches a short version of a git hash. Then git checkout might be ambiguous

2021-08-26 07:59 UTC, sgiehl commented on docs/git.md
> +After you added or modified a few files you will want to push these changes to the remote repository. It's good to commit regularly even if a feature is not finished yet so you always have a backup i
```suggestion
After you added or modified a few files you will want to push these changes to the remote repository. It's good to commit and push regularly even if a feature is not finished yet so you always have a backup if changes get lost for some reason.
```

2021-08-26 07:59 UTC, sgiehl commented on docs/git.md
> +git commit --amend -m 'My awesome commit message'
Should we mention that a force push is needed when amending a commit that was already pushed?

2021-08-26 07:59 UTC, sgiehl commented on docs/git.md
> +#### Undo last commit that is not pushed yet without losing the changes
This can also be used to undo a commit that had been pushed, but it will then require a force push

2021-08-26 21:44 UTC, tsteur commented on docs/git.md
> +* [Git LFS needs to be installed](https://github.com/git-lfs/git-lfs/wiki/Installation)
they used to be cloned by default or not? Are you saying after `git clone` we now need to execute `git lfs pull --exclude=` everywhere including the submodules?

2021-08-26 21:48 UTC, tsteur commented on docs/git.md
> +git commit --amend -m 'My awesome commit message'
I'll add a note to not amend commits after pushing

2021-08-26 21:48 UTC, tsteur commented
Cheers @sgiehl I'm still in the process of writing the guide but incorporated some things already

2021-08-26 21:49 UTC, sgiehl commented
For most submodules the UI files aren't stored on LFS. But yes this needs
to be executed at least in matomo repo as our gitconfig prevent the
checkout by default.

2021-09-02 21:38 UTC, justinvelluppillai approved these changes
Looks good, a lot of nice tips in here. I wonder if we could produce a one page cheat sheet along the same lines at some point.

2021-09-02 21:38 UTC, merged