Add caters to PWA to SPA
piwik/developer-documentation pull request #614
Opened 2022-02-20 22:11 UTC by peterhashair

### Description:

 Add caters to PWA to SPA

Follow the request here https://github.com/matomo-org/matomo/issues/18066

### Review

* [ ] [Functional review done](https://developer.matomo.org/guides/pull-request-reviews#functional-review-done)
* [ ] [Potential edge cases thought about](https://developer.matomo.org/guides/pull-request-reviews#potential-edge-cases-thought-about) (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [ ] [Usability review done](https://developer.matomo.org/guides/pull-request-reviews#usability-review-done) (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] [Security review done](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] [Wording review done](https://developer.matomo.org/guides/pull-request-reviews#translations-wording-review-done)
* [ ] [Code review done](https://developer.matomo.org/guides/pull-request-reviews#code-review-done)
* [ ] [Tests were added if useful/possible](https://developer.matomo.org/guides/pull-request-reviews#tests-were-added-if-usefulpossible)
* [ ] [Reviewed for breaking changes](https://developer.matomo.org/guides/pull-request-reviews#reviewed-for-breaking-changes)
* [ ] [Developer changelog updated if needed](https://developer.matomo.org/guides/pull-request-reviews#developer-changelog-updated-if-needed)
* [ ] [Documentation added if needed](https://developer.matomo.org/guides/pull-request-reviews#documentation-added-if-needed)
* [ ] Existing documentation updated if needed

2022-02-20 22:20 UTC, Findus23 requested changes
Just some minor text changes.

2022-02-20 22:20 UTC, Findus23 commented on docs/4.x/spa-tracking.md
> +Single-page websites and Progressive Web App have become a standard over the last years. Getting the tracking of such websites and apps right is crucial to your success as you need to ensure the meas
```suggestion
Single-page websites and Progressive Web Apps have become a standard over the last years. Getting the tracking of such websites and apps right is crucial to your success as you need to ensure the measured data is meaningful and correct.
```

2022-02-20 22:20 UTC, Findus23 commented on docs/4.x/spa-tracking.md
> +If your web application require offline tracking, refer [Matomo Offline Tracking](https://matomo.org/faq/how-to/how-do-i-set-up-matomo-offline-tracking/)
```suggestion
If your web application requires offline tracking, please refer to the [Matomo  offline tracking](https://matomo.org/faq/how-to/how-do-i-set-up-matomo-offline-tracking/) guide.
```

2022-02-21 11:16 UTC, sgiehl commented on docs/4.x/spa-tracking.md
> +If your web application requires offline tracking, please refer to the [Matomo  offline tracking](https://matomo.org/faq/how-to/how-do-i-set-up-matomo-offline-tracking/) guide.
```suggestion
If your web application requires offline tracking, please refer to the [Matomo offline tracking](https://matomo.org/faq/how-to/how-do-i-set-up-matomo-offline-tracking/) guide.
```

2022-03-01 23:05 UTC, merged