Make sure data layer examples work no matter where they are copied
piwik/developer-documentation pull request #621
Opened 2022-03-14 19:45 UTC by tsteur

Sometimes people copy these examples not into the website using a `script` tag but into their regular JS code. Copy/Pasting this code into a regular function can cause issues as _mtm may then only exist locally. For many `_paq` examples we have already changed it to `window._paq` .

By using "window." when accessing the _mtm dataLayer variable it'll always work no matter if it's executed in global context or a local context.

I didn't check any other files or docs if it's missing there too.

### Review

* [ ] [Functional review done](https://developer.matomo.org/guides/pull-request-reviews#functional-review-done)
* [ ] [Potential edge cases thought about](https://developer.matomo.org/guides/pull-request-reviews#potential-edge-cases-thought-about) (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [ ] [Usability review done](https://developer.matomo.org/guides/pull-request-reviews#usability-review-done) (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] [Security review done](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] [Wording review done](https://developer.matomo.org/guides/pull-request-reviews#translations-wording-review-done)
* [ ] [Code review done](https://developer.matomo.org/guides/pull-request-reviews#code-review-done)
* [ ] [Tests were added if useful/possible](https://developer.matomo.org/guides/pull-request-reviews#tests-were-added-if-usefulpossible)
* [ ] [Reviewed for breaking changes](https://developer.matomo.org/guides/pull-request-reviews#reviewed-for-breaking-changes)
* [ ] [Developer changelog updated if needed](https://developer.matomo.org/guides/pull-request-reviews#developer-changelog-updated-if-needed)
* [ ] [Documentation added if needed](https://developer.matomo.org/guides/pull-request-reviews#documentation-added-if-needed)
* [ ] Existing documentation updated if needed

2022-03-15 02:25 UTC, AltamashShaikh commented
@tsteur Updated all the occurrences of `_mtm` to `window._mtm`

2022-03-15 02:31 UTC, tsteur reviewed
@AltamashShaikh sorry I just realise what I did wasn't quite correct. I checked the code we use in Tag Manager and it is actually this:

```
var _mtm = window._mtm = window._mtm || [];
```

That's because otherwise, if `window._mtm` doesn't exist yet, then the newly defined array would only exist within the local context.

Another way could be:

```
window._mtm = window._mtm || [];
window._mtm.push('...')
```

2022-04-12 22:53 UTC, justinvelluppillai commented on docs/4.x/tagmanager/datalayer.md
> +As the container will be loaded asynchronously and the variable `_mtm` may not be defined from the beginning, you may have to add a `var _mtm = window._mtm || [];`.
```suggestion
As the container will be loaded asynchronously and the variable `_mtm` may not be defined from the beginning, you may have to add a `window._mtm = window._mtm || [];`.
```

2022-04-12 22:54 UTC, justinvelluppillai commented on docs/4.x/tagmanager/debugging.md
> +var _mtm = window._mtm || [];
```suggestion
window._mtm = window._mtm || [];
```

2022-04-12 22:54 UTC, justinvelluppillai commented on docs/4.x/tagmanager/integration-plugin.md
> +var _mtm = window._mtm || [];
```suggestion
window._mtm = window._mtm || [];
```

2022-04-12 22:54 UTC, justinvelluppillai commented on docs/4.x/tagmanager/integration-plugin.md
>  _mtm.push({'mtm.startTime': (new Date().getTime()), 'event': 'mtm.Start'});
```suggestion
window._mtm.push({'mtm.startTime': (new Date().getTime()), 'event': 'mtm.Start'});
```

2022-04-12 22:55 UTC, justinvelluppillai requested changes
Looks like a few missed, have commented on each for you to double check.

2022-04-13 02:13 UTC, AltamashShaikh commented
@justinvelluppillai Updated all the references, please check

2022-04-13 03:24 UTC, justinvelluppillai approved these changes

2022-04-13 03:26 UTC, merged